{"name": "test_a", "status": "failed", "statusDetails": {"message": "AssertionError: assert '789' == '78'\n  - 78\n  + 789\n  ?   +", "trace": "self = <test_image.TestImage object at 0x0000023103E8C278>\n\n    def test_a(self):\n        a = \"789\"\n        b = \"78\"\n>       assert a == b\nE       AssertionError: assert '789' == '78'\nE         - 78\nE         + 789\nE         ?   +\n\ntestcase\\test_image.py:14: AssertionError"}, "start": 1669272416808, "stop": 1669272416808, "uuid": "9723b297-ac5f-44a8-b176-038319449549", "historyId": "255f37ca6f69848c2260d1175ac71030", "testCaseId": "f63154bd7a4f5957149869338ef4fdd8", "fullName": "testcase.test_image.TestImage#test_a", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_image"}, {"name": "subSuite", "value": "TestImage"}, {"name": "host", "value": "CNENGewN2GAcDkx"}, {"name": "thread", "value": "19056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_image"}]}