{"uid":"1f9131c6bf1a51ec","name":"test_api","fullName":"testcase.test_1#test_api","historyId":"f50ce33f5630f142ce687d98cf4b15af","time":{"start":1669601661211,"stop":1669601661211,"duration":0},"status":"broken","statusMessage":"AttributeError: module pytest has no attribute unique_id","statusTrace":"@pytest.mark.xfail(pytest.__version__ < '0.2.0',\n                       reason='not supported until v0.2.0')\n    def test_api():\n>       id_1 = pytest.unique_id()\n\ntestcase\\test_1.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nname = 'unique_id'\n\n    def __getattr__(name: str) -> object:\n        if name == \"Instance\":\n            # The import emits a deprecation warning.\n            from _pytest.python import Instance\n    \n            return Instance\n>       raise AttributeError(f\"module {__name__} has no attribute {name}\")\nE       AttributeError: module pytest has no attribute unique_id\n\nvenv\\lib\\site-packages\\pytest\\__init__.py:169: AttributeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.xfail(False, reason='not supported until v0.2.0')"},{"name":"parentSuite","value":"testcase"},{"name":"suite","value":"test_1"},{"name":"host","value":"CNENGewN2GAcDkx"},{"name":"thread","value":"17164-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcase.test_1"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.xfail(False, reason='not supported until v0.2.0')"]},"source":"1f9131c6bf1a51ec.json","parameterValues":[]}